image: ubuntu:latest

stages:
  - deploy
  - release

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - apt update && apt upgrade -y
  - apt install python3 python3-pip -y
  - python3 -V  # Print out python version for debugging
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate

wheel-deploy:
  stage: deploy
  only:
    - tags
  script:
    - pip3 install --upgrade setuptools wheel pep517
    - python3 -m pep517.build .
    - pip install dist/$CI_PROJECT_NAME-$CI_COMMIT_TAG-py3-none-any.whl
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - dist/*.whl

wheel-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo 'Wheel release $CI_COMMIT_TAG'
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'wheel release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
  dependencies:
    - wheel-deploy