image: ubuntu:latest

stages:
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - apt update && apt upgrade -y
  - apt install python3 python3-pip -y
  - python3 -V  # Print out python version for debugging
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate

release:
  stage: deploy
#  only:
#    - tags
  script:
    - pip3 install --upgrade setuptools wheel pep517
    - python3 -m pep517.build .
    - ls
