image: ubuntu:latest

stages:
  - test
  - deploy

variables:
  CI_COMMIT_TAG_DUMMY: "1.0.0"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - apt update && apt upgrade -y
  - apt install python3 python3-pip -y
  - python3 -V  # Print out python version for debugging
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test_whl:
  stage: test
  script:
    - pip install --upgrade setuptools wheel pep517
    - python3 -m pep517.build .
    - pip install dist/$CI_PROJECT_NAME-$CI_COMMIT_TAG_DUMMY-py3-none-any.whl

release:
  stage: deploy
  only:
    - tags
  script:
    - pip3 install --upgrade setuptools wheel pep517
    - python3 -m pep517.build .
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - dist/*.whl
